// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/application": {
            "get": {
                "description": "Returns the full in-memory application snapshot.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Application snapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ApplicationSnapshot"
                        }
                    }
                }
            }
        },
        "/api/controller": {
            "get": {
                "description": "Returns controller counters and current request offset.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controller"
                ],
                "summary": "Controller summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ControllerSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/controller/nodes": {
            "get": {
                "description": "Returns nodes currently known by the controller.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controller"
                ],
                "summary": "List connected controller nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ControllerNodesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/controller/ping-requests": {
            "get": {
                "description": "Returns controller-managed ping requests using offset pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controller"
                ],
                "summary": "List controller ping requests",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Read offset",
                        "name": "from_offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Node ID for heartbeat registration",
                        "name": "X-Node-ID",
                        "in": "header"
                    },
                    {
                        "type": "number",
                        "description": "Node latitude",
                        "name": "X-Node-Lat",
                        "in": "header"
                    },
                    {
                        "type": "number",
                        "description": "Node longitude",
                        "name": "X-Node-Lon",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Node organization",
                        "name": "X-Node-Organization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Node role",
                        "name": "X-Node-Role",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ControllerPingRequestsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a ping request directly on the controller and dispatches it locally.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controller"
                ],
                "summary": "Create controller ping request",
                "parameters": [
                    {
                        "description": "Ping request payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateControllerPingRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.PingRequestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/controller/ping-requests/{id}/results": {
            "get": {
                "description": "Returns a controller request and the results collected for it so far.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controller"
                ],
                "summary": "Get controller ping request results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ping request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ControllerPingRequestResultsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/controller/ping-results": {
            "post": {
                "description": "Stores a ping result for an existing controller request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "controller"
                ],
                "summary": "Submit controller ping result",
                "parameters": [
                    {
                        "description": "Ping result payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PingResult"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.AcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/node": {
            "get": {
                "description": "Returns local node metadata and queue counters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "Node summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.NodeSummaryResponse"
                        }
                    }
                }
            }
        },
        "/api/node/ping-requests": {
            "get": {
                "description": "Returns ping requests submitted by the current node.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "List submitted node requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.NodePingRequestsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a ping request through the configured upstream controller.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "Create node ping request",
                "parameters": [
                    {
                        "description": "Ping request payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateNodePingRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.PingRequestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/node/ping-requests/{id}/results": {
            "get": {
                "description": "Refreshes and returns results for a submitted node ping request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node"
                ],
                "summary": "Get node ping request results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ping request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PingResultsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns backend health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Configuration": {
            "type": "object",
            "properties": {
                "staleNodeAfter": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "controller.Snapshot": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/controller.Configuration"
                },
                "state": {
                    "$ref": "#/definitions/controller.StateSnapshot"
                }
            }
        },
        "controller.StateSnapshot": {
            "type": "object",
            "properties": {
                "connected_nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConnectedNode"
                    }
                },
                "ping_requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PingRequest"
                    }
                },
                "ping_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PingResult"
                    }
                }
            }
        },
        "main.AcceptedResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "accepted"
                }
            }
        },
        "main.ApplicationSnapshot": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/main.Config"
                },
                "controller": {
                    "$ref": "#/definitions/controller.Snapshot"
                },
                "node": {
                    "$ref": "#/definitions/node.Snapshot"
                }
            }
        },
        "main.Config": {
            "type": "object",
            "properties": {
                "controllerURL": {
                    "type": "string"
                },
                "httptimeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "isController": {
                    "type": "boolean"
                },
                "listenAddr": {
                    "type": "string"
                },
                "nodeID": {
                    "type": "string"
                },
                "pollInterval": {
                    "$ref": "#/definitions/time.Duration"
                },
                "staleNodeAfter": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "main.ControllerNodesResponse": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConnectedNode"
                    }
                }
            }
        },
        "main.ControllerPingRequestResultsResponse": {
            "type": "object",
            "properties": {
                "collecting": {
                    "type": "boolean"
                },
                "request": {
                    "$ref": "#/definitions/model.PingRequest"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PingResult"
                    }
                }
            }
        },
        "main.ControllerPingRequestsResponse": {
            "type": "object",
            "properties": {
                "current_offset": {
                    "type": "integer",
                    "example": 140
                },
                "next_offset": {
                    "type": "integer",
                    "example": 100
                },
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PingRequest"
                    }
                }
            }
        },
        "main.ControllerSummaryResponse": {
            "type": "object",
            "properties": {
                "connected_nodes": {
                    "type": "integer",
                    "example": 4
                },
                "current_offset": {
                    "type": "integer",
                    "example": 12
                },
                "ping_requests": {
                    "type": "integer",
                    "example": 8
                },
                "ping_results": {
                    "type": "integer",
                    "example": 16
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "main.CreateControllerPingRequestBody": {
            "type": "object",
            "required": [
                "target"
            ],
            "properties": {
                "source_node_id": {
                    "type": "string",
                    "example": "node-west-1"
                },
                "target": {
                    "type": "string",
                    "example": "example.com"
                }
            }
        },
        "main.CreateNodePingRequestBody": {
            "type": "object",
            "required": [
                "target"
            ],
            "properties": {
                "target": {
                    "type": "string",
                    "example": "1.1.1.1"
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "request not found"
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "main.NodePingRequestsResponse": {
            "type": "object",
            "properties": {
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SubmittedPingRequest"
                    }
                }
            }
        },
        "main.NodeSummaryResponse": {
            "type": "object",
            "properties": {
                "current_offset": {
                    "type": "integer",
                    "example": 12
                },
                "is_controller": {
                    "type": "boolean"
                },
                "node": {
                    "$ref": "#/definitions/model.NodeInfo"
                },
                "submitted_requests": {
                    "type": "integer",
                    "example": 3
                },
                "upstream_controller": {
                    "type": "string",
                    "example": "http://controller:8081"
                }
            }
        },
        "main.PingRequestResponse": {
            "type": "object",
            "properties": {
                "request": {
                    "$ref": "#/definitions/model.PingRequest"
                }
            }
        },
        "main.PingResultsResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PingResult"
                    }
                }
            }
        },
        "model.ConnectedNode": {
            "type": "object",
            "properties": {
                "last_contact": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/model.Location"
                },
                "node_id": {
                    "type": "string"
                },
                "organization": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.NodeRole"
                }
            }
        },
        "model.Location": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "model.NodeIdentity": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/model.Location"
                },
                "node_id": {
                    "type": "string"
                },
                "organization": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.NodeRole"
                }
            }
        },
        "model.NodeInfo": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/model.Location"
                },
                "node_id": {
                    "type": "string"
                },
                "organization": {
                    "type": "string"
                },
                "public_ip": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.NodeRole"
                }
            }
        },
        "model.NodeRole": {
            "type": "string",
            "enum": [
                "worker",
                "controller",
                "hybrid"
            ],
            "x-enum-varnames": [
                "NodeRoleWorker",
                "NodeRoleController",
                "NodeRoleHybrid"
            ]
        },
        "model.PingRequest": {
            "type": "object",
            "properties": {
                "collect_until": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "source_node_id": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "model.PingResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "executor": {
                    "$ref": "#/definitions/model.NodeIdentity"
                },
                "latency_ms": {
                    "type": "number"
                },
                "observed_at": {
                    "type": "string"
                },
                "reporter_node_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.SubmittedPingRequest": {
            "type": "object",
            "properties": {
                "cached_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PingResult"
                    }
                },
                "last_results_sync_at": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/model.PingRequest"
                }
            }
        },
        "node.Configuration": {
            "type": "object",
            "properties": {
                "httptimeout": {
                    "$ref": "#/definitions/time.Duration"
                },
                "identity": {
                    "$ref": "#/definitions/model.NodeInfo"
                },
                "pollInterval": {
                    "$ref": "#/definitions/time.Duration"
                },
                "upstreamURL": {
                    "type": "string"
                }
            }
        },
        "node.Snapshot": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/node.Configuration"
                },
                "state": {
                    "$ref": "#/definitions/node.StateSnapshot"
                }
            }
        },
        "node.StateSnapshot": {
            "type": "object",
            "properties": {
                "current_offset": {
                    "type": "integer"
                },
                "executed_request_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "offset_known": {
                    "type": "boolean"
                },
                "relayed_result_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "submitted_requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SubmittedPingRequest"
                    }
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Distributed Ping API",
	Description:      "HTTP API for distributed ping nodes and controller coordination.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
